version: '3.8'
services:
  node:
    build: .
    command: "npm start"
    working_dir: /home/node/app
    expose:
      - "3000"
    ports:
      - '3000:3000'
  db:
    image: mysql/mysql-server:latest
    container_name: my-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=mysqlDB
      - MYSQL_ROOT_PASSWORD=mysqlPW
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
    driver: local